Repository LikeLion13-Team1/Team1-BackEnd, pull requests merged in 2025-07, with the labels that each got.

#27 ✨ Feat/#8: 루틴 기능 구현
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/RoutineDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/exception/RoutineErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/routine/exception/RoutineException.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
Labels: ✨feature

#28 루틴 기본 CRUD
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/RoutineDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/exception/RoutineErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/routine/exception/RoutineException.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
Labels: ✨feature

#30 ✨ Feat/#20: 루틴 이벤트 기능 구현
  src/main/java/com/project/likelion13th_team1/domain/alarm/entity/Alarm.java
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
  src/main/java/com/project/likelion13th_team1/domain/event/converter/EventConverter.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/EventDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/request/EventRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/response/EventResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/entity/Event.java
  src/main/java/com/project/likelion13th_team1/domain/event/exception/EventErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/event/exception/EventException.java
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/RoutineEvent.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Status.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/entity/RoutineStatus.java
Labels: ✨feature

#33 💚 ci/cd/#32: git action 설정
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 💚ci/cd

#34 cicd 기본 설정 & application.yml 분리 & redis 기반 설치 / main 적용 (Gyueon)
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 💚ci/cd

#36 🐛fix: CorsConfig 설정 변경
  src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
  src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
Labels: 🚑!HOTFIX

#37 🐛fix: Cors Error Fix
  src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
Labels: 🚑!HOTFIX

#38 Feat/#7-4: 멤버 유효성
  src/main/java/com/project/likelion13th_team1/domain/member/controller/MemberController.java
  src/main/java/com/project/likelion13th_team1/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/project/likelion13th_team1/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/project/likelion13th_team1/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/likelion13th_team1/global/security/utils/PasswordPattern.java
Labels: ✨feature

#39 Feat/#8-2 루틴 유효성 검증 & 이벤트 기능 구현
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
  src/main/java/com/project/likelion13th_team1/domain/event/converter/EventConverter.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/request/EventRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/response/EventResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/entity/Event.java
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Cycle.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/project/likelion13th_team1/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/likelion13th_team1/global/entity/Status.java
Labels: ✨feature

#43 유효성 검사 & 로그아웃 & 스웨거 주석
  build.gradle
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
  src/main/java/com/project/likelion13th_team1/domain/event/converter/EventConverter.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/request/EventRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/response/EventResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/entity/Event.java
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/controller/MemberController.java
  src/main/java/com/project/likelion13th_team1/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Cycle.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/project/likelion13th_team1/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/likelion13th_team1/global/entity/Status.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/controller/AuthController.java
  src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
  src/main/java/com/project/likelion13th_team1/global/security/filter/CustomLogoutHandler.java
  src/main/java/com/project/likelion13th_team1/global/security/filter/CustomLogoutSuccessHandler.java
  src/main/java/com/project/likelion13th_team1/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/likelion13th_team1/global/security/jwt/JwtUtil.java
  src/main/java/com/project/likelion13th_team1/global/security/utils/PasswordPattern.java
Labels: ✨feature

#46 🐛fix: 토큰 재발급이 allowUrl에 포함되지 않았던 오류
  src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
Labels: 🐛fix

#47 Feat/#45: 루틴 그룹 추가
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/group/controller/GroupController.java
  src/main/java/com/project/likelion13th_team1/domain/group/converter/GroupConverter.java
  src/main/java/com/project/likelion13th_team1/domain/group/dto/GroupDto.java
  src/main/java/com/project/likelion13th_team1/domain/group/dto/request/GroupRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/group/dto/response/GroupResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/group/entity/Group.java
  src/main/java/com/project/likelion13th_team1/domain/group/exception/GroupErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/group/exception/GroupException.java
  src/main/java/com/project/likelion13th_team1/domain/group/repository/GroupRepository.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/query/GroupQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/query/GroupQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
Labels: ✨feature

#48 Feat/#8-3 : 루틴 반복기준 변경
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
  src/main/java/com/project/likelion13th_team1/domain/event/converter/EventConverter.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/request/EventRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/dto/response/EventResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/event/entity/Event.java
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/controller/MemberController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/request/RoutineRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/dto/response/RoutineResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
Labels: ✨feature

#52 Feat/#8-5: 이벤트 스케줄러 구현
  src/main/java/com/project/likelion13th_team1/Likelion13thTeam1Application.java
  src/main/java/com/project/likelion13th_team1/domain/event/scheduler/EventScheduler.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
Labels: ✨feature

#26 ✨ feat/#17: 멤버십 API 구현
  build.gradle
  src/main/java/com/project/likelion13th_team1/domain/member/controller/MemberController.java
  src/main/java/com/project/likelion13th_team1/domain/member/converter/MemberConverter.java
  src/main/java/com/project/likelion13th_team1/domain/member/dto/request/MembeRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/member/entity/Member.java
  src/main/java/com/project/likelion13th_team1/domain/member/entity/MemberFeature.java
  src/main/java/com/project/likelion13th_team1/domain/member/exception/MemberErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/member/exception/MemberException.java
  src/main/java/com/project/likelion13th_team1/domain/member/repository/MemberRepository.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/membership/controller/MembershipController.java
  src/main/java/com/project/likelion13th_team1/domain/membership/converter/MembershipConverter.java
  src/main/java/com/project/likelion13th_team1/domain/membership/dto/response/MembershipResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/membership/entity/Membership.java
  src/main/java/com/project/likelion13th_team1/domain/membership/exception/MembershipErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/membership/exception/MembershipException.java
  src/main/java/com/project/likelion13th_team1/domain/membership/repository/MembershipRepository.java
  src/main/java/com/project/likelion13th_team1/domain/membership/service/command/MembershipCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/membership/service/command/MembershipCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/membership/service/query/MembershipQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/membership/service/query/MembershipQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/Routine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/RoutineFeature.java
  src/main/java/com/project/likelion13th_team1/global/feature/converter/FeatureConverter.java
  src/main/java/com/project/likelion13th_team1/global/feature/dto/request/FeatureRequestDto.java
  src/main/java/com/project/likelion13th_team1/global/feature/dto/response/FeatureResponseDto.java
  src/main/java/com/project/likelion13th_team1/global/feature/entity/CleanHouse.java
  src/main/java/com/project/likelion13th_team1/global/feature/entity/CleaningStyle.java
  src/main/java/com/project/likelion13th_team1/global/feature/entity/Feature.java
  src/main/java/com/project/likelion13th_team1/global/feature/entity/FeatureType.java
  src/main/java/com/project/likelion13th_team1/global/feature/entity/MessyHouse.java
  src/main/java/com/project/likelion13th_team1/global/feature/entity/RoutineStyle.java
  src/main/java/com/project/likelion13th_team1/global/feature/repository/FeatureRepository.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/controller/AuthController.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/dto/request/AuthRequestDto.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/handler/CustomLoginFilter.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/service/AuthService.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/service/AuthServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
  src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
  src/main/java/com/project/likelion13th_team1/global/security/exception/AuthErrorCode.java
  src/main/java/com/project/likelion13th_team1/global/security/exception/AuthException.java
  src/main/java/com/project/likelion13th_team1/global/security/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/com/project/likelion13th_team1/global/security/exception/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/project/likelion13th_team1/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/likelion13th_team1/global/security/jwt/JwtUtil.java
  src/main/java/com/project/likelion13th_team1/global/security/jwt/dto/JwtDto.java
  src/main/java/com/project/likelion13th_team1/global/security/jwt/entity/Token.java
  src/main/java/com/project/likelion13th_team1/global/security/jwt/repository/TokenRepository.java
  src/main/java/com/project/likelion13th_team1/global/security/userdetails/CustomUserDetails.java
  src/main/java/com/project/likelion13th_team1/global/security/userdetails/service/CustomUserDetailsService.java
  src/main/resources/application.yml
Labels: ✨feature

#57 Feat/#14-4 카카오 로그인 구현
  src/main/java/com/project/likelion13th_team1/domain/feature/converter/FeatureConverter.java
  src/main/java/com/project/likelion13th_team1/domain/feature/entity/Feature.java
  src/main/java/com/project/likelion13th_team1/domain/feature/repository/FeatureRepository.java
  src/main/java/com/project/likelion13th_team1/domain/feature/service/command/FeatureCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/feature/service/query/FeatureQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/controller/MemberController.java
  src/main/java/com/project/likelion13th_team1/domain/member/converter/MemberConverter.java
  src/main/java/com/project/likelion13th_team1/domain/member/converter/SocialLoginConverter.java
  src/main/java/com/project/likelion13th_team1/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/project/likelion13th_team1/domain/member/entity/Member.java
  src/main/java/com/project/likelion13th_team1/domain/member/entity/SocialLogin.java
  src/main/java/com/project/likelion13th_team1/domain/member/repository/MemberRepository.java
  src/main/java/com/project/likelion13th_team1/domain/member/repository/SocialLoginRepository.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/converter/AuthConverter.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/entity/Auth.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/repository/AuthRepository.java
  src/main/java/com/project/likelion13th_team1/global/security/config/SecurityConfig.java
  src/main/java/com/project/likelion13th_team1/global/security/kakao/controller/KakaoLoginController.java
  src/main/java/com/project/likelion13th_team1/global/security/kakao/dto/response/KakaoTokenResponseDto.java
  src/main/java/com/project/likelion13th_team1/global/security/kakao/dto/response/KakaoUserInfoResponseDto.java
  src/main/java/com/project/likelion13th_team1/global/security/kakao/service/KakaoService.java
  src/main/java/com/project/likelion13th_team1/global/security/userdetails/service/CustomUserDetailsService.java
  src/main/resources/application-prod.yml
Labels: ✨feature

#60 🚀chore: CorsConfig에 PATCH 추가
  src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
Labels: ✨feature, 🐛fix

#61 Feat/#49-2: 특성 응답 바디에 총점수 추가
  src/main/java/com/project/likelion13th_team1/domain/feature/converter/FeatureConverter.java
  src/main/java/com/project/likelion13th_team1/domain/feature/dto/response/FeatureResponseDto.java
Labels: ✨feature

#63 Webflux 의존성 추가
  build.gradle
Labels: ✨feature

#67 Feat/#8-6: 목록 조회 편의성 증가
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
Labels: ✨feature

#70 🚀chore: uri 수정
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
Labels: ✨feature, 🐛fix

#69 루틴 목록 조회 편하게 & 루틴 추천 구현
  src/main/java/com/project/likelion13th_team1/domain/event/controller/EventController.java
  src/main/java/com/project/likelion13th_team1/domain/event/repository/EventRepository.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/feature/controller/FeatureController.java
  src/main/java/com/project/likelion13th_team1/domain/feature/converter/FeatureConverter.java
  src/main/java/com/project/likelion13th_team1/domain/feature/dto/response/FeatureResponseDto.java
  src/main/java/com/project/likelion13th_team1/domain/feature/entity/Feature.java
  src/main/java/com/project/likelion13th_team1/domain/feature/exception/FeatureErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/feature/service/command/FeatureCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/feature/service/query/FeatureQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/group/controller/GroupController.java
  src/main/java/com/project/likelion13th_team1/domain/group/exception/GroupErrorCode.java
  src/main/java/com/project/likelion13th_team1/domain/group/repository/GroupRepository.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/entity/Member.java
  src/main/java/com/project/likelion13th_team1/domain/member/entity/Personality.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/converter/RoutineConverter.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/ExampleRoutine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/entity/RecommendedRoutine.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/ExampleRoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RecommendedRoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/command/RoutineCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
Labels: ✨feature

#71 ✨feat: 회원 가입 시 그룹 3개 자동 생성
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
Labels: ✨feature

#72 최초 회원가입 시 루틴 그룹 자동 생성 (Gyueon)
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/command/GroupCommandServiceImpl.java
  src/main/java/com/project/likelion13th_team1/domain/member/service/command/MemberCommandServiceImpl.java
Labels: ✨feature

#77 Feat/#45-4: 그룹 기능 수정
  README.md
  src/main/java/com/project/likelion13th_team1/domain/group/controller/GroupController.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/query/GroupQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/query/GroupQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/security/config/CorsConfig.java
Labels: 🐛fix

#78 그룹 단일 검색이 모든 그룹에 검색되던 문제 해결 & 비밀번호 변경 구현 & uri 수정
  src/main/java/com/project/likelion13th_team1/domain/group/controller/GroupController.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/query/GroupQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/group/service/query/GroupQueryServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/controller/AuthController.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/dto/request/AuthRequestDto.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/entity/Auth.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/service/AuthService.java
  src/main/java/com/project/likelion13th_team1/global/security/auth/service/AuthServiceImpl.java
  src/main/java/com/project/likelion13th_team1/global/security/exception/AuthErrorCode.java
Labels: ✨feature

#85 그룹 목록 조회에서 isActive인 루틴만 반환하는 기능 구현
  src/main/java/com/project/likelion13th_team1/domain/routine/controller/RoutineController.java
  src/main/java/com/project/likelion13th_team1/domain/routine/repository/RoutineRepository.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryService.java
  src/main/java/com/project/likelion13th_team1/domain/routine/service/query/RoutineQueryServiceImpl.java
Labels: ✨feature

#89 ✨feat: 메일 의존성 추가
  build.gradle
Labels: ✨feature
